---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Lucuma: Exporter → Importer → Country (MT)

Fusion Foods C,DISTRIBUIDORA LATINOANDINA,26
DISTRIBUIDORA LATINOANDINA,Spain,26
NATURANDINA AMERICA,Spain,22
The Green Farmer C,NATURANDINA AMERICA,14
TO ORDER,Spain,12
Fusion Foods C,TO ORDER,11
Miranda Langa Agro Export Cmiranda Langa C,NATURANDINA AMERICA,4
Exportaciones Mirsa Empresa Individual D,NATURANDINA AMERICA,4
Zowi Peru,JOTA JOTA ALIMENTOS GLOBAL,3
JOTA JOTA ALIMENTOS GLOBAL,Spain,3
Miranda Langa Agro Export Cmiranda Langa C,TO ORDER,2
Mikuy Traders C,BEBIDAS Y ALIMENTOS EUROPA,1
BEBIDAS Y ALIMENTOS EUROPA,Spain,1
TO ORDER,Italy,1
Other Exporters,Other Importers,1
Other Importers,Spain,1