---
config:
  theme: base
  themeVariables:
    fontSize: 18px
  sankey:
    showValues: true
---
sankey-beta

%% All Fruits to Germany: Exporter → Fruit → Importer → Country (MT)

HG FOOD,Germany,2876
Mango,HG FOOD,2010
CAMPOSOL,Blueberry,1344
Blueberry,ISCHROEDER,1080
ISCHROEDER,Germany,1080
AGROINDUSTRIA FRUTOS DE ORO,Mango,986
Blueberry,HG FOOD,818
FRUTOS TROPICALES,Mango,742
HENRY LAMOTTE FOOD,Germany,680
AGROINDUSTRIAS AIB,Avocado,678
Avocado,HENRY LAMOTTE FOOD,678
Mango,KURT PIJAHN HANDELSGESELLSCHAFT MBH,529
KURT PIJAHN HANDELSGESELLSCHAFT MBH,Germany,529
ARA FOODS INDUSTRY,Mango,478
SANTA SOFIA DEL SUR,Mango,456
FRUTOS TROPICALES,Blueberry,434
FRUTICAL,Blueberry,432
Unknown,Germany,288
Blueberry,SKOGSMAT IUDDEHOLM,266
SKOGSMAT IUDDEHOLM,Germany,266
Blueberry,MEYER GEMUSEBEARBEITUNG,260
MEYER GEMUSEBEARBEITUNG,Germany,260
Mango,CENTRAL IMPORT MUNSTER,240
CENTRAL IMPORT MUNSTER,Germany,240
MEBOL GF,Blueberry,216
Mango,BINDER,212
BINDER,Germany,212
GLOBAL FOOD LINK,Germany,200
Blueberry,Unknown,168
Blueberry,GLOBAL FOOD LINK,157
PROFRUIT INDUSTRY,Mango,144
COMPLEJO AGROINDUSTRIAL BETA,Blueberry,133
MEBOL,Blueberry,120
Mango,Unknown,120
VIRU,Mango,112
PROCESADORA,Mango,96
AMARA FOODS,Avocado,78
DANPER TRUJILLO,Blueberry,72
GANADERA CHAVIN DE HUANTAR,Mango,72
Pineapple,HG FOOD,48
Blueberry,AMVEL,48
Mango,CENTRALIMPORT CO NEVINGHO,48
AMVEL,Germany,48
CENTRALIMPORT CO NEVINGHO,Germany,48
Blueberry,MB GLOBAL FOODS,48
MB GLOBAL FOODS,Germany,48
EXPORTACIONES MIRSA EMPRESA INDIVIDUAL,Blueberry,44
Avocado,GLOBAL FOOD LINK,43
TO ORDER,Germany,39
Avocado,TO ORDER,35
PROCESADORA,Pineapple,24
Blueberry,GREENYARD FROZEN,24
GREENYARD FROZEN,Germany,24
AGROEMPAQUES,Blueberry,24
FRUTOS TONGORRAPE,Mango,24
FUSION FOODS,Blueberry,24
GAMN EXPORT IMPORT SERV GNRAL,Blueberry,24
MEBOL,Mango,24
MEBOL GF,Mango,24
PULPAS Y PROCESADOS DEL AGRO PULPAGRO,Mango,24
SELVA INDUSTRIAL,Pineapple,24
UNION DE NEGOCIOS CORPORATIVOS,Blueberry,24
WESTFALIA FRUIT PERU,Mango,24
Mango,ALLFOOD,24
Mango,CENTRAL IMPORT GMGH,24
Mango,RANSON,24
ALLFOOD,Germany,24
CENTRAL IMPORT GMGH,Germany,24
RANSON,Germany,24
CAMPOSOL,Mango,23
AGROINDUSTRIAS AIB,Mango,22
Blueberry,ARDO FOODS,22
ARDO FOODS,Germany,22
DEL ANDE ALIMENTOS,Mango,19
Mango,CONCEPT COOL VERTRIEBSGESELLSCHAFT MBH,19
CONCEPT COOL VERTRIEBSGESELLSCHAFT MBH,Germany,19
Mango,EDEKA IMPORT LOGISTIK,18
EDEKA IMPORT LOGISTIK,Germany,18
SUNSHINE EXPORT,Avocado,16
Avocado,CPF DENMARK,16
CPF DENMARK,Germany,16
AMARA FOODS,Unknown,4
Unknown,TO ORDER,4
Mango,HENRY LAMOTTE FOOD,2