---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Avocado to Germany: Exporter → Importer → Country (MT)

AGROINDUSTRIAS AIB,HENRY LAMOTTE FOOD,678
HENRY LAMOTTE FOOD,Germany,678
AMARA FOODS,GLOBAL FOOD LINK,43
GLOBAL FOOD LINK,Germany,43
AMARA FOODS,TO ORDER,35
TO ORDER,Germany,35
SUNSHINE EXPORT,CPF DENMARK,16
CPF DENMARK,Germany,16