---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Grape: Exporter → Importer → Country (MT)

Dominus C,ARDO FOODS,110
ARDO FOODS,United Kingdom,110
Dominus C,LEON VINCENT OVERSEAS,22
LEON VINCENT OVERSEAS,France,22
Dominus C,DARTA,8
DARTA,Belgium,8
Dominus C,NEWBERRY PRODUCE,3
NEWBERRY PRODUCE,Other Countries,3
Dominus C,Other Importers,3
Other Importers,France,3