---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Papaya: Exporter → Importer → Country (MT)

Exportaciones Mirsa Empresa Individual D,DECA,1
DECA,Spain,1
Mikuy Traders C,BEBIDAS Y ALIMENTOS EUROPA,1
BEBIDAS Y ALIMENTOS EUROPA,Spain,1
Lamas Import Export C,VAPER FOODS,0
VAPER FOODS,Spain,0