---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Mango to Germany: Exporter → Importer → Country (MT)

HG FOOD,Germany,2010
FRUTOS TROPICALES,HG FOOD,718
KURT PIJAHN HANDELSGESELLSCHAFT MBH,Germany,529
AGROINDUSTRIA FRUTOS DE ORO,KURT PIJAHN HANDELSGESELLSCHAFT MBH,506
SANTA SOFIA DEL SUR,HG FOOD,456
ARA FOODS INDUSTRY,HG FOOD,382
CENTRAL IMPORT MUNSTER,Germany,240
BINDER,Germany,212
AGROINDUSTRIA FRUTOS DE ORO,BINDER,192
AGROINDUSTRIA FRUTOS DE ORO,CENTRAL IMPORT MUNSTER,192
PROFRUIT INDUSTRY,HG FOOD,144
Unknown,Germany,120
ARA FOODS INDUSTRY,Unknown,96
PROCESADORA,HG FOOD,96
VIRU,HG FOOD,94
AGROINDUSTRIA FRUTOS DE ORO,CENTRALIMPORT CO NEVINGHO,48
AGROINDUSTRIA FRUTOS DE ORO,HG FOOD,48
GANADERA CHAVIN DE HUANTAR,CENTRAL IMPORT MUNSTER,48
CENTRALIMPORT CO NEVINGHO,Germany,48
FRUTOS TONGORRAPE,ALLFOOD,24
FRUTOS TROPICALES,Unknown,24
GANADERA CHAVIN DE HUANTAR,RANSON,24
MEBOL,HG FOOD,24
MEBOL GF,CENTRAL IMPORT GMGH,24
PULPAS Y PROCESADOS DEL AGRO PULPAGRO,HG FOOD,24
WESTFALIA FRUIT PERU,HG FOOD,24
ALLFOOD,Germany,24
CENTRAL IMPORT GMGH,Germany,24
RANSON,Germany,24
CAMPOSOL,KURT PIJAHN HANDELSGESELLSCHAFT MBH,23
AGROINDUSTRIAS AIB,BINDER,20
DEL ANDE ALIMENTOS,CONCEPT COOL VERTRIEBSGESELLSCHAFT MBH,19
CONCEPT COOL VERTRIEBSGESELLSCHAFT MBH,Germany,19
VIRU,EDEKA IMPORT LOGISTIK,18
EDEKA IMPORT LOGISTIK,Germany,18
AGROINDUSTRIAS AIB,HENRY LAMOTTE FOOD,2
HENRY LAMOTTE FOOD,Germany,2