---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Avocado: Exporter → Importer → Country (MT)

SALUD FOODGROUP EUROPE,Netherlands,7595
Other Importers,Other Countries,4067
SYROS,Belgium,3382
FOODFELLAS,United Kingdom,2849
DARTA,Belgium,2760
AGROEMPAQUES,SALUD FOODGROUP EUROPE,2564
Sunshine Export C,SALUD FOODGROUP EUROPE,2526
Sunshine Export C,DARTA,2375
Other Exporters,Other Importers,2353
AGROINDUSTRIAS AIB,Other Importers,2228
VIRU IBERICA,Other Countries,1680
Amara Foods C,GLOBAL FOOD LINK,1615
Other Importers,Belgium,1532
Viru Group Peru,Unknown,1481
Other Importers,Netherlands,1396
VIRU,VIRU IBERICA,1382
Other Exporters,Westfalia Fruit Uk,1313
Other Exporters,SYROS,1257
Westfalia Fruit Uk,United Kingdom,1254
GLOBAL FOOD LINK,Other Countries,1204
Other Importers,United Kingdom,1118
Agroindustria Frutos De Oro C,Other Importers,1102
GLOBAL FOOD LINK,Belgium,1048
Agroindustria Frutos De Oro C,SYROS,1042
Viru Group Peru,SALUD FOODGROUP EUROPE,979
ARDO FOODS,Belgium,967
Other Exporters,SALUD FOODGROUP EUROPE,954
Agricola Y Ganadera Chavin De Huantar,FOODFELLAS,917
Foodimpex International,Other Countries,903
Unknown,Netherlands,903
AGROINDUSTRIAS AIB,FOODFELLAS,894
AGROINDUSTRIAS AIB,SYROS,871
Unknown,Other Countries,785
Agricola Y Ganadera Chavin De Huantar,Other Importers,753
VIRU,SALUD FOODGROUP EUROPE,732
Other Exporters,ARDO FOODS,716
AGROINDUSTRIAS AIB,HENRY LAMOTTE FOOD,678
HENRY LAMOTTE FOOD,Other Countries,678
PATRIGEL,Other Countries,614
Sunshine Export C,FOODFELLAS,601
Amara Foods C,TO ORDER,585
Sunshine Export C,Other Importers,581
Labeyrie Fine Foods France,Other Countries,576
Viru Group Peru,Foodimpex International,566
Agricola Y Ganadera Chavin De Huantar,GLOBAL FOOD LINK,555
Viru Group Peru,Other Importers,536
SALUD FOODGROUP EUROPE,Other Countries,514
VIRU,Other Importers,513
Agricola Y Ganadera Chavin De Huantar,SALUD FOODGROUP EUROPE,464
Other Exporters,CROPS VEGETABLES,431
CROPS VEGETABLES,Other Countries,408
Sunshine Export C,Labeyrie Fine Foods France,336
GLOBAL FOOD LINK,United Kingdom,334
TO ORDER,Belgium,328
VIRU,PATRIGEL,327
Viru Group Peru,VIRU IBERICA,298
Viru Group Peru,PATRIGEL,287
TO ORDER,Other Countries,281
VIRU,Foodimpex International,256
Other Exporters,GLOBAL FOOD LINK,244
Other Exporters,DARTA,222
Viru Group Peru,ARDO FOODS,220
Other Exporters,Unknown,219
VIRU,FOODFELLAS,199
SALUD FOODGROUP EUROPE,United Kingdom,192
AGROINDUSTRIAS AIB,DARTA,187
Unknown,United Kingdom,176
Agroindustria Frutos De Oro C,GLOBAL FOOD LINK,173
VIRU,Unknown,166
VIRU,ARDO FOODS,159
VIRU,SYROS,148
CROPS VEGETABLES,Belgium,144
Unknown,Belgium,133
Agricola Y Ganadera Chavin De Huantar,CROPS VEGETABLES,120
Sunshine Export C,SYROS,101
AGROINDUSTRIAS AIB,SALUD FOODGROUP EUROPE,101
AGROEMPAQUES,FOODFELLAS,96
AGROEMPAQUES,Labeyrie Fine Foods France,96
Agroindustria Frutos De Oro C,FOODFELLAS,96
VIRU,Labeyrie Fine Foods France,96
Other Exporters,TO ORDER,83
ARDO FOODS,Other Countries,72
AGROINDUSTRIAS AIB,Unknown,67
Other Exporters,Foodimpex International,63
TO ORDER,United Kingdom,59
Westfalia Fruit Uk,Netherlands,59
ARDO FOODS,United Kingdom,56
Agricola Y Ganadera Chavin De Huantar,Labeyrie Fine Foods France,48
Viru Group Peru,FOODFELLAS,46
Sunshine Export C,Unknown,41
AGROEMPAQUES,Other Importers,24
DARTA,Netherlands,24
Amara Foods C,Other Importers,23
Amara Foods C,Unknown,23
SYROS,Netherlands,20
SALUD FOODGROUP EUROPE,Belgium,20
Sunshine Export C,Foodimpex International,19
SYROS,United Kingdom,17