---
config:
  sankey:
    showValues: false
---
sankey-beta

%% Mango: Exporter → Importer → Country (MT)

Other Importers,Other Countries,2426
CROPS FRUITS,Belgium,2371
HG FOOD,Germany,2010
DARTA,Belgium,1618
Other Exporters,Other Importers,1411
VIRU IBERICA,Other Countries,1172
Other Importers,Netherlands,1141
Other Importers,Belgium,1083
VIRU,Other Importers,1038
Sunshine Export C,DARTA,984
Agroindustria Frutos De Oro C,Other Importers,951
AGROINDUSTRIAS AIB,CROPS FRUITS,948
VIRU,VIRU IBERICA,940
GREENYARD FROZEN,Belgium,939
FROSINN,Netherlands,912
3BERRY,Poland,893
POLARICA,Poland,836
Frutos Tropicales Peru Export,HG FOOD,790
Fruticola Olmue Peru C,CROPS FRUITS,783
Other Exporters,3BERRY,773
DESCOURS,Other Countries,759
Santa Sofia Del Sur C,HG FOOD,756
Other Exporters,HG FOOD,742
Other Exporters,SONDERJANSEN,634
SONDERJANSEN,Netherlands,634
NETRA,Netherlands,623
Other Exporters,GREENYARD FROZEN,577
Viru Group Peru,Unknown,572
Agricola Y Ganadera Chavin De Huantar,CROPS FRUITS,572
Agricola Y Ganadera Chavin De Huantar,Other Importers,554
SALUD FOODGROUP EUROPE,Netherlands,540
KURT PIJAHN HANDELSGESELLSCHAFT MBH,Germany,529
FLAGFOOD,Netherlands,528
AGROCONGELADOS LA CUERVA,Other Countries,508
Agroindustria Frutos De Oro C,KURT PIJAHN HANDELSGESELLSCHAFT MBH,506
Frutos Tropicales Peru Export,FROSINN,504
FRUITS ROUGES AND,Belgium,480
GREENYARD FROZEN,Other Countries,452
Unknown,Poland,440
ZUMDIECK,Netherlands,432
VIRU,POLARICA,418
CAMPOSOL,AGROCONGELADOS LA CUERVA,418
Fruticola Olmue Peru C,Other Importers,408
Fruticola Olmue Peru C,DESCOURS,403
Other Importers,Poland,395
HG FOOD,Belgium,384
Other Exporters,FRUITS ROUGES AND,360
Agroindustria Frutos De Oro C,FROSINN,336
Other Exporters,Norrek Dypfrys As,312
Norrek Dypfrys As,Other Countries,312
Unknown,Other Countries,308
Agroindustria Frutos De Oro C,ZUMDIECK,288
ARDO FOODS,Other Countries,286
Agroindustria Frutos De Oro C,BINDER,286
Frutos Tropicales Peru Export,Other Importers,283
Dominus C,DARTA,270
GREENYARD FROZEN,Poland,264
CAMPOSOL,GREENYARD FROZEN,264
Fruticola Olmue Peru C,FLAGFOOD,264
Other Exporters,DESCOURS,245
CAMPOSOL,DARTA,244
CENTRAL,Germany,240
VIRU,NETRA,239
VIRU,SALUD FOODGROUP EUROPE,237
Viru Group Peru,VIRU IBERICA,232
Sunshine Export C,POLARICA,220
Other Exporters,NETRA,219
Agroindustria Frutos De Oro C,CENTRAL,214
Agricola Y Ganadera Chavin De Huantar,GREENYARD FROZEN,214
BINDER,Germany,212
VIRU,Foodimpex International,207
Foodimpex International,Other Countries,206
AGROINDUSTRIAS AIB,Other Importers,203
Viru Group Peru,SALUD FOODGROUP EUROPE,184
Agricola Y Ganadera Chavin De Huantar,CENTRAL,182
CENTRAL,Other Countries,176
Agroindustria Frutos De Oro C,GREENYARD FROZEN,168
Sunshine Export C,GREENYARD FROZEN,168
Agricola Y Ganadera Chavin De Huantar,FLAGFOOD,168
Unknown,Belgium,166
Other Importers,Germany,159
VIRU,ARDO FOODS,154
Dominus C,ZUMDIECK,144
Other Exporters,Unknown,144
Sunshine Export C,Other Importers,144
AGROINDUSTRIAS AIB,3BERRY,120
Agricola Y Ganadera Chavin De Huantar,DARTA,120
Santa Sofia Del Sur C,NETRA,120
Unknown,Germany,120
Fruticola Olmue Peru C,GREENYARD FROZEN,120
Sunshine Export C,SALUD FOODGROUP EUROPE,120
Dominus C,Other Importers,118
Dominus C,ARDO FOODS,110
CAMPOSOL,POLARICA,110
CAMPOSOL,Unknown,110
Frutos Tropicales Peru Export,GREENYARD FROZEN,96
HG FOOD,Netherlands,96
Agroindustria Frutos De Oro C,FLAGFOOD,96
Agroindustria Frutos De Oro C,HG FOOD,96
Sunshine Export C,Unknown,96
Foodimpex International,Netherlands,96
VIRU,Unknown,96
BINDER,Poland,94
VIRU,HG FOOD,94
Dominus C,DESCOURS,89
Viru Group Peru,POLARICA,88
CAMPOSOL,Other Importers,74
Dominus C,FRUITS ROUGES AND,72
VIRU,FROSINN,72
Other Exporters,AGROCONGELADOS LA CUERVA,66
CAMPOSOL,CROPS FRUITS,66
HG FOOD,Other Countries,60
AGROINDUSTRIAS AIB,FRUITS ROUGES AND,48
Other Exporters,CENTRAL,48
Other Exporters,Foodimpex International,48
Sunshine Export C,CROPS FRUITS,48
Viru Group Peru,GREENYARD FROZEN,48
CENTRAL,Netherlands,48
Viru Group Peru,Foodimpex International,47
CROPS FRUITS,Other Countries,46
Dominus C,CENTRAL,44
Unknown,Netherlands,32
AGROINDUSTRIAS AIB,FLAGFOOD,24
AGROINDUSTRIAS AIB,HG FOOD,24
Agroindustria Frutos De Oro C,AGROCONGELADOS LA CUERVA,24
Agroindustria Frutos De Oro C,NETRA,24
Dominus C,HG FOOD,24
Frutos Tropicales Peru Export,Unknown,24
Viru Group Peru,HG FOOD,24
CENTRAL,Belgium,24
FLAGFOOD,Belgium,24
Fruticola Olmue Peru C,Unknown,24
Agroindustria Frutos De Oro C,DESCOURS,23
CAMPOSOL,KURT PIJAHN HANDELSGESELLSCHAFT MBH,23
CAMPOSOL,ARDO FOODS,22
Viru Group Peru,NETRA,21
AGROINDUSTRIAS AIB,BINDER,20
Viru Group Peru,Other Importers,20