---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Blueberry to Germany: Exporter → Importer → Country (MT)

ISCHROEDER,Germany,1080
CAMPOSOL,ISCHROEDER,1008
HG FOOD,Germany,818
FRUTOS TROPICALES,HG FOOD,410
CAMPOSOL,SKOGSMAT IUDDEHOLM,266
SKOGSMAT IUDDEHOLM,Germany,266
MEYER GEMUSEBEARBEITUNG,Germany,260
FRUTICAL,MEYER GEMUSEBEARBEITUNG,216
MEBOL GF,HG FOOD,216
Unknown,Germany,168
GLOBAL FOOD LINK,Germany,157
COMPLEJO AGROINDUSTRIAL BETA,GLOBAL FOOD LINK,133
FRUTICAL,Unknown,96
MEBOL,HG FOOD,96
DANPER TRUJILLO,ISCHROEDER,72
FRUTICAL,HG FOOD,72
AMVEL,Germany,48
CAMPOSOL,MB GLOBAL FOODS,48
MB GLOBAL FOODS,Germany,48
EXPORTACIONES MIRSA EMPRESA INDIVIDUAL,MEYER GEMUSEBEARBEITUNG,44
FRUTICAL,GREENYARD FROZEN,24
GREENYARD FROZEN,Germany,24
AGROEMPAQUES,AMVEL,24
FRUTICAL,GLOBAL FOOD LINK,24
FRUTOS TROPICALES,Unknown,24
FUSION FOODS,HG FOOD,24
GAMN EXPORT IMPORT SERV GNRAL,Unknown,24
MEBOL,Unknown,24
UNION DE NEGOCIOS CORPORATIVOS,AMVEL,24
CAMPOSOL,ARDO FOODS,22
ARDO FOODS,Germany,22