---
config:
  sankey:
    showValues: false
---
sankey-beta

%% Blueberry: Exporter → Importer → Country (MT)

GREENYARD FROZEN,United Kingdom,1573
Other Importers,Other Countries,1417
Camposol,GREENYARD FROZEN,1276
Other Exporters,Other Importers,1096
Frutical,GREENYARD FROZEN,1056
Camposol,I SCHROEDER KG GMBH and CO,984
I SCHROEDER KG GMBH and CO,Germany,984
Camposol,ARDO FOODS,890
ARDO FOODS,United Kingdom,890
HG FOOD,Germany,794
POLARICA,Poland,770
NEWBERRY INTERNATIONAL PRODUCE,United Kingdom,754
Camposol,Other Importers,740
Camposol,ARDO FOODS NV ASHFORD SITE,726
ARDO FOODS NV ASHFORD SITE,United Kingdom,704
BESTFOODS POLSKA,Poland,677
ZUMDIECK,Other Countries,674
Other Exporters,Unknown,661
Other Importers,Germany,633
Camposol,SKOGSMAT I UDDEHOLM,576
Beta,Other Importers,560
GREENYARD FROZEN,Poland,552
Camposol,ZUMDIECK,528
Unknown,Poland,510
GREENYARD FROZEN,Other Countries,504
Other Importers,United Kingdom,495
Other Exporters,POLARICA,462
Unknown,United Kingdom,450
Other Importers,Poland,448
Frutos Tropicales Peru,HG FOOD,434
DARTA,Other Countries,352
Mebol,HG FOOD,336
Frutos Tropicales Peru,Other Importers,335
Camposol,NEWBERRY INTERNATIONAL PRODUCE,324
Camposol,DARTA,308
Camposol,POLARICA,286
Other Exporters,NEWBERRY INTERNATIONAL PRODUCE,286
SKOGSMAT I UDDEHOLM,Other Countries,286
Other Exporters,BESTFOODS POLSKA,281
SKOGSMAT I UDDEHOLM,Germany,266
Camposol,Unknown,266
Frutical,Other Importers,240
Mebol,BESTFOODS POLSKA,240
Other Exporters,GREENYARD FROZEN,225
Beta,BESTFOODS POLSKA,202
Frutical,Unknown,168
Unknown,Germany,168
Unknown,Other Countries,159
Beta,NEWBERRY INTERNATIONAL PRODUCE,144
Other Exporters,ZUMDIECK,144
Beta,Unknown,72
Frutical,HG FOOD,72
Mebol,GREENYARD FROZEN,72
Mebol,Unknown,72
Frutos Tropicales Peru,Unknown,48
HG FOOD,Other Countries,48
BESTFOODS POLSKA,Other Countries,46
Mebol,DARTA,44
Frutos Tropicales Peru,GREENYARD FROZEN,24
GREENYARD FROZEN,Germany,24
Frutical,NEWBERRY INTERNATIONAL PRODUCE,24
NEWBERRY INTERNATIONAL PRODUCE,Poland,24
SKOGSMAT I UDDEHOLM,United Kingdom,24
Mebol,ZUMDIECK,24
Mebol,POLARICA,22
ARDO FOODS NV ASHFORD SITE,Germany,22
ZUMDIECK,United Kingdom,22
Mebol,Other Importers,22