---
config:
  theme: base
  themeVariables:
    fontSize: 18px
  sankey:
    showValues: false
---
sankey-beta

%% Mango: Exporter → Importer → Country (MT)

Other Importers,Other Countries,2562
CROPS FRUITS,Belgium,2415
HG FOOD,Germany,2010
DARTA,Belgium,1618
VIRU,Other Importers,1211
VIRU,VIRU IBERICA,1172
VIRU IBERICA,Other Countries,1172
Other Importers,Netherlands,1165
Other Exporters,Other Importers,1089
SUNSHINE EXPORT,DARTA,984
AGROINDUSTRIA FRUTOS DE ORO,Other Importers,975
AGROINDUSTRIAS AIB,CROPS FRUITS,948
GREENYARD FROZEN,Belgium,939
FROSINN,Netherlands,912
POLARICA,Poland,858
3BERRY,Poland,821
FRUTOS TROPICALES,HG FOOD,790
FRUTICOLA OLMUE PERU,CROPS FRUITS,783
DESCOURS,Other Countries,759
SANTA SOFIA DEL SUR,HG FOOD,756
Other Importers,Belgium,753
Other Exporters,3BERRY,749
Other Exporters,HG FOOD,742
VIRU,Unknown,668
Other Exporters,SONDERJANSEN,634
SONDERJANSEN,Netherlands,634
NETRA,Netherlands,623
Other Exporters,GREENYARD FROZEN,577
GANADERA CHAVIN DE HUANTAR,CROPS FRUITS,572
GANADERA CHAVIN DE HUANTAR,Other Importers,554
SALUD FOODGROUP EUROPE,Netherlands,540
KURT PIJAHN HANDELSGESELLSCHAFT MBH,Germany,529
FLAGFOOD,Netherlands,528
AGROCONGELADOS LA CUERVA,Other Countries,508
AGROINDUSTRIA FRUTOS DE ORO,KURT PIJAHN HANDELSGESELLSCHAFT MBH,506
VIRU,POLARICA,506
FRUTOS TROPICALES,FROSINN,504
FRUITS ROUGES AND,Belgium,480
GREENYARD FROZEN,Other Countries,452
Other Importers,Poland,445
Unknown,Poland,440
VIRU,SALUD FOODGROUP EUROPE,421
CAMPOSOL,AGROCONGELADOS LA CUERVA,418
ZUMDIECK,Netherlands,408
FRUTICOLA OLMUE PERU,DESCOURS,403
HG FOOD,Belgium,384
Other Exporters,FRUITS ROUGES AND,360
FRUTICOLA OLMUE PERU,Other Importers,341
AGROINDUSTRIA FRUTOS DE ORO,FROSINN,336
Other Exporters,NORREK DYPFRYS,312
NORREK DYPFRYS,Other Countries,312
Unknown,Other Countries,308
FOODIMPEX,Other Countries,289
AGROINDUSTRIA FRUTOS DE ORO,BINDER,286
BERRYMARK,Belgium,286
FRUTOS TROPICALES,Other Importers,283
DOMINUS,DARTA,270
GREENYARD FROZEN,Poland,264
AGROINDUSTRIA FRUTOS DE ORO,ZUMDIECK,264
CAMPOSOL,GREENYARD FROZEN,264
FRUTICOLA OLMUE PERU,FLAGFOOD,264
Other Exporters,BERRYMARK,264
VIRU,NETRA,260
VIRU,FOODIMPEX,255
AGROINDUSTRIAS AIB,Other Importers,251
Other Exporters,DESCOURS,245
CAMPOSOL,DARTA,244
CENTRAL IMPORT MUNSTER,Other Countries,244
CENTRAL IMPORT MUNSTER,Germany,240
SUNSHINE EXPORT,POLARICA,220
Other Exporters,NETRA,219
AGROINDUSTRIA FRUTOS DE ORO,CENTRAL IMPORT MUNSTER,214
GANADERA CHAVIN DE HUANTAR,GREENYARD FROZEN,214
BINDER,Germany,212
DOMINUS,Other Importers,206
GANADERA CHAVIN DE HUANTAR,CENTRAL IMPORT MUNSTER,182
AGROINDUSTRIA FRUTOS DE ORO,GREENYARD FROZEN,168
SUNSHINE EXPORT,GREENYARD FROZEN,168
GANADERA CHAVIN DE HUANTAR,FLAGFOOD,168
Unknown,Belgium,166
Other Importers,Germany,159
DOMINUS,ZUMDIECK,144
Other Exporters,Unknown,144
SUNSHINE EXPORT,Other Importers,144
CAMPOSOL,POLARICA,132
Other Exporters,FOODIMPEX,130
GANADERA CHAVIN DE HUANTAR,DARTA,120
SANTA SOFIA DEL SUR,NETRA,120
Unknown,Germany,120
FRUTICOLA OLMUE PERU,GREENYARD FROZEN,120
SUNSHINE EXPORT,SALUD FOODGROUP EUROPE,120
VIRU,HG FOOD,118
CAMPOSOL,CROPS FRUITS,110
CAMPOSOL,Unknown,110
FRUTOS TROPICALES,GREENYARD FROZEN,96
HG FOOD,Netherlands,96
AGROINDUSTRIA FRUTOS DE ORO,FLAGFOOD,96
AGROINDUSTRIA FRUTOS DE ORO,HG FOOD,96
SUNSHINE EXPORT,Unknown,96
FOODIMPEX,Netherlands,96
BINDER,Poland,94
DOMINUS,DESCOURS,89
AGROINDUSTRIAS AIB,3BERRY,72
DOMINUS,FRUITS ROUGES AND,72
VIRU,FROSINN,72
FRUTICOLA OLMUE PERU,CENTRAL IMPORT MUNSTER,68
Other Exporters,AGROCONGELADOS LA CUERVA,66
HG FOOD,Other Countries,60
AGROINDUSTRIAS AIB,FRUITS ROUGES AND,48
Other Exporters,CENTRAL IMPORT MUNSTER,48
SUNSHINE EXPORT,CROPS FRUITS,48
VIRU,GREENYARD FROZEN,48
CENTRAL IMPORT MUNSTER,Netherlands,48
CROPS FRUITS,Other Countries,46
DOMINUS,CENTRAL IMPORT MUNSTER,44
Unknown,Netherlands,32
CAMPOSOL,Other Importers,30
AGROINDUSTRIA FRUTOS DE ORO,AGROCONGELADOS LA CUERVA,24
AGROINDUSTRIA FRUTOS DE ORO,NETRA,24
AGROINDUSTRIAS AIB,FLAGFOOD,24
AGROINDUSTRIAS AIB,HG FOOD,24
DOMINUS,HG FOOD,24
FRUTOS TROPICALES,Unknown,24
CENTRAL IMPORT MUNSTER,Belgium,24
FLAGFOOD,Belgium,24
FRUTICOLA OLMUE PERU,Unknown,24
AGROINDUSTRIA FRUTOS DE ORO,DESCOURS,23
CAMPOSOL,KURT PIJAHN HANDELSGESELLSCHAFT MBH,23
DOMINUS,BERRYMARK,22
AGROINDUSTRIAS AIB,BINDER,20