---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Blueberry: Exporter → Importer → Country (MT)

Other Importers,Other Countries,1821
ARDO FOODS,United Kingdom,1736
CAMPOSOL,ARDO FOODS,1664
GREENYARD FROZEN,United Kingdom,1573
CAMPOSOL,GREENYARD FROZEN,1276
ISCHROEDER,Germany,1080
Frutical C,GREENYARD FROZEN,1056
Other Exporters,Other Importers,1025
CAMPOSOL,Other Importers,1021
CAMPOSOL,ISCHROEDER,1008
HG FOOD,Germany,794
POLARICA,Poland,770
NEWBERRY PRODUCE,United Kingdom,754
BESTFOODS,Poland,677
GREENYARD FROZEN,Poland,600
DARTA,Other Countries,598
CAMPOSOL,SKOGSMAT IUDDEHOLM,576
Complejo Agroindustrial Beta,Other Importers,560
Other Importers,Germany,537
Unknown,Poland,510
GREENYARD FROZEN,Other Countries,504
CAMPOSOL,DARTA,484
Other Exporters,BESTFOODS,473
Frutos Tropicales Peru Export,HG FOOD,458
Unknown,United Kingdom,450
Other Exporters,Unknown,445
Sunshine Export C,POLARICA,418
Other Importers,Poland,400
Other Importers,United Kingdom,375
Other Exporters,HG FOOD,336
CAMPOSOL,NEWBERRY PRODUCE,324
CAMPOSOL,POLARICA,286
Other Exporters,NEWBERRY PRODUCE,286
SKOGSMAT IUDDEHOLM,Other Countries,286
SKOGSMAT IUDDEHOLM,Germany,266
CAMPOSOL,Unknown,266
Danper Trujillo C,Unknown,264
Frutos Tropicales Peru Export,Other Importers,263
Frutical C,Other Importers,240
Complejo Agroindustrial Beta,BESTFOODS,202
Frutical C,Unknown,168
Unknown,Germany,168
Unknown,Other Countries,159
Danper Trujillo C,GREENYARD FROZEN,153
Complejo Agroindustrial Beta,NEWBERRY PRODUCE,144
Other Exporters,DARTA,114
Other Exporters,ARDO FOODS,94
Frutos Tropicales Peru Export,GREENYARD FROZEN,72
Complejo Agroindustrial Beta,Unknown,72
Danper Trujillo C,ISCHROEDER,72
Frutical C,HG FOOD,72
Other Exporters,GREENYARD FROZEN,72
HG FOOD,Other Countries,72
Sunshine Export C,GREENYARD FROZEN,72
Other Exporters,POLARICA,66
Danper Trujillo C,BESTFOODS,48
Frutos Tropicales Peru Export,Unknown,48
BESTFOODS,Other Countries,46
GREENYARD FROZEN,Germany,24
Frutical C,NEWBERRY PRODUCE,24
Sunshine Export C,Other Importers,24
NEWBERRY PRODUCE,Poland,24
SKOGSMAT IUDDEHOLM,United Kingdom,24
Sunshine Export C,Unknown,24
ARDO FOODS,Germany,22