---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Passion_Fruit: Exporter → Importer → Country (MT)

Agricola Y Ganadera Chavin De Huantar,CROPS FRUITS,55
CROPS FRUITS,Belgium,55
Other Exporters,Other Importers,46
Flymexport Peru E Ir,Tropical Fresh,39
Tropical Fresh,Belgium,39
Other Importers,Spain,36
Fusion Foods C,TO ORDER,24
Amara Foods C,SAPREX HANDELS,24
SAPREX HANDELS,Netherlands,24
TO ORDER,Estonia,22
Fusion Foods C,ESTMA OU,20
ESTMA OU,Estonia,20
Amara Foods C,GLOBAL FOOD LINK,18
GLOBAL FOOD LINK,Spain,17
Other Importers,Other Countries,6
Other Importers,United Kingdom,4
TO ORDER,Spain,2
GLOBAL FOOD LINK,United Kingdom,1
Amara Foods C,Other Importers,1
Other Importers,Netherlands,1