---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Golden_Berry: Exporter → Importer → Country (MT)

FRUTOS TONGORRAPE,CARRIERE,8
Peruvian Food Groups,Barth Fruit 25 Ch Basel,8
Barth Fruit 25 Ch Basel,Netherlands,8
CARRIERE,Netherlands,8