---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Banana: Exporter → Importer → Country (MT)

Dominus C,FRUIT MANAGEMENT EUROPE,21
FRUIT MANAGEMENT EUROPE,Netherlands,21
Lamas Import Export C,VAPER FOODS,11
VAPER FOODS,Spain,11
Exportaciones Mirsa Empresa Individual D,PREMIER FOODS WHOLESALE,5
PREMIER FOODS WHOLESALE,United Kingdom,5
Other Exporters,Giovannis Import,1
Other Exporters,Other Importers,1
Giovannis Import,Spain,1
Other Importers,Spain,1
Exportaciones Mirsa Empresa Individual D,Other Importers,1
Other Importers,United Kingdom,1