---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Pineapple: Exporter → Importer → Country (MT)

Procesadora Peru,HG FOOD,72
SELVA INDUSTRIAL,TO ORDER,67
TO ORDER,Netherlands,67
HG FOOD,Germany,48
HG FOOD,Netherlands,48
Other Importers,United Kingdom,27
PACIFIC IQF,FLAGFOOD,25
FLAGFOOD,Netherlands,25
Procesadora Laran,Other Importers,24
Procesadora Peru,Other Importers,24
SELVA INDUSTRIAL,HG FOOD,24
Other Importers,Belgium,24
Exportaciones Mirsa Empresa Individual D,Other Importers,4
Other Importers,Other Countries,3
Exportaciones Mirsa Empresa Individual D,TO ORDER,2
TO ORDER,United Kingdom,2
Lamas Import Export C,Other Importers,1
Other Exporters,Other Importers,0
Other Importers,Netherlands,0