---
config:
  sankey:
    showValues: true
---
sankey-beta

%% Soursop: Exporter → Importer → Country (MT)

Lamas Import Export C,VAPER FOODS,7
VAPER FOODS,Spain,7
Mikuy Traders C,BEBIDAS Y ALIMENTOS EUROPA,0
BEBIDAS Y ALIMENTOS EUROPA,Spain,0
Fusion Foods C,TO ORDER,0
TO ORDER,Spain,0